### PR TITLE
feat: added card details with card transfer and licitation deck

### PR DESCRIPTION
**Pull request by MaxKolodziej**
Hey,
I really appreciate your idea for the app and I wanted to extend it,
I've added licitation deck on the start + new houses ( Tleilaxu, Ixians, Richese & Choam )
There are card details when you click on the the card
You can transfer cards between houses & licitation deck.

I'm a newbie when comes to Android Apps, so sorry for my mistakes :) This code probably could look better

### CODE REVIEW

**Comment by frike00** [comment]
Hi, new here.
where apk can be downloaded?

**Comment by MaxKolodziej** [comment]
@frike00 
Here are the links:
  https://drive.google.com/file/d/1H8ci3PPMG48YGNkoBlFSCiOoQE7BtJ0_/view?usp=sharing
  
  zipped-version: https://drive.google.com/file/d/1hf5X01jDyEJAXOP8Q1-U5Yo7wUN4FVOS/view?usp=share_link

**Comment by MaxKolodziej** [comment]
I've added post with links on https://boardgamegeek.com/thread/3088374/updated-application-attreides-card-tracking

**Comment by frike00** [comment]
thanks

and some cards could get different icona instead of Hand icon. just to
differentiate some. also blue thunder icon is missing representing special
defence.

uto, 23. svi 2023. 16:04 Maksymilian Kołodziej ***@***.***>
je napisao:

**Comment by MaxKolodziej** [comment]
@frike00 could you help me with those icons? Those should be transparent PNG images with 175x175, for example like this: https://raw.githubusercontent.com/mktiti/AtreidesTreacheryTracker/054ff605d10861465b593e782ad24ef723084b50/app/src/main/assets/icons/factions/atreides.png

If you'll help me it will be quicker to update this app ;)

**Comment by mktiti** [comment]
Hey guys!
I'm so sorry I haven't had time yet to look through the changes, but promise to do so next week.
Thanks for not just taking interest in the project, but also contributing -- really appreciate it!
Cheers!

**Comment by frike00** [comment]
[image: def special.png]

  for defence special cards (shield sbooper,
chemistry)



[image: Richese 175.png]
for richese special cards put this icon


and karama kards[image: karama 175.png]

**Comment by MaxKolodziej** [comment]
@frike00 I cannot see those images here nor in the email, could you attach it here in the REPO comment

**Comment by frike00** [comment]
https://drive.google.com/drive/folders/1F17oSEii8gY5VnQ39WmY3hqj5cCJ05vP

sri, 31. svi 2023. 12:56 Maksymilian Kołodziej ***@***.***>
je napisao:

**Comment by MaxKolodziej** [comment]
@frike00 I need access :)

**Comment by frike00** [comment]
Done.

sri, 31. svi 2023. 13:36 Maksymilian Kołodziej ***@***.***>
je napisao:

**Comment by MaxKolodziej** [comment]
@frike00 I've added new version: https://drive.google.com/file/d/1OdqRTSV00369MlwVimiZcf-C_EGKMQCz/view?usp=sharing
Pls. remove application cache in android settings to make this work

**Comment by frike00** [comment]
thanx

1)
*residual poison*
*distrans*

should be richese special cards not with hand icon.

2) Also 1 karama card is from Richese special cards (if it is possible to
add that one only)

3) Artillery Strike is a Special attack weapon (red thunder icon!)

4) Also Worthless cards should have additional description text that if
CHOAM faction uses them, only:
Baliset -  Prevent a player from moving forces into a territory you occupy
during Shipment and Movement. They may ship in normally.
Jubba Cloak -  Prevent a loss of your forces in one territory to the Storm
when it moves.
Kull Wahad -  Prevent a player from playing a Karama card this phase as
they attempt to do so.
Kulon -  Move your forces one extra territory on your turn in Shipping and
Movement.
La La La - Prevent a player from taking Free Revival during Revival.
Trip to Gamont -  Send any 1 force belonging to another player to that
player’s reserves during the Mentat Pause

4) Also I am giving you more icons to differentiate cards better.
Family atomics
Truth trance
Hajr
Tleilaxu ghola

(see the Drive)




sri, 31. svi 2023. 21:14 Maksymilian Kołodziej ***@***.***>
je napisao:

**Comment by frike00** [comment]
Also, Choam should hold 5 cards instead of 4.

**Comment by MaxKolodziej** [comment]
@frike00 I've added new version 1.2:
https://drive.google.com/file/d/1MJtaTVVdIBytBhTH776MPbU-pru0p5_Y/view?usp=sharing

Pls. remove application cache in android settings to make this work

**Comment by frike00** [comment]
Thanks, it worked.

pet, 16. lip 2023. 18:08 Maksymilian Kołodziej ***@***.***>
je napisao:

**Comment by frike00** [comment]
Hi
its me again. New card are ready to give you (new expansion). Sending you
soon.

Also is it posible to install apk to Android 4?

sub, 17. lip 2023. 10:34 Samir R ***@***.***> je napisao:

**Comment by frike00** [comment]
Hi
it would be a great dune community service to do the following. During
multiple plays, the app deemed very useful with few useful changes for
easier finding cards.

Poison tooth icon:

[image: Poison tooth 175.png]



Cheap hero:

[image: cheap hero 175.png]




Harvester:

[image: Harvester 175.png]




Thumper:
[image: thumper 175.png]




Family atomics:
[image: family atomics 175.png]




Artillery strike:

[image: Artillery strike 175.png]


Amal:

[image: amal 175.png]


Weirding way
[image: Wierding way 175.png]




Lasgun

[image: Lasgun175.png]


Weather control

[image: weather control 175 .png]











*Also NEWEST FRACTIONS:*

*Moritani:*
Hand limit 4. When terror token Atomics used, hand limit = 3
[image: MORITANI 175.png]


*Ecaz:*
Hand limit 4.

[image: ecaz 175.png]






*New Treachery cards*
*Recruits*
Play during Revival.
All Factions double their current Free Revival rates.
The normal revival limit is increased to 7.
Discard after use.


[image: RECRUITS 175.png]





*Reinforcements*
Play as part of your Battle Plan in place of a weapon or defence.
Add +2 to your dialed number, then send 3 forces from your reserves to the
Tanks.
You may not use this card if you do not have at least 3 forces in your
reserves.
Discard after use.

[image: reinforcements 175.png]







*Harass & Withdraw*
Play as part of your Battle Plan in place of a weapon or defence.
Your undialed forces return to your reserves. Your leader may still be
killed normally. If your opponent calls Traitor, this effect is canceled.
Aface Dancer caller on your leader has no effect on your undialed forces.
Do not use when on your Homeworld.
Discard after use.
[image: Harass 175.png]






*Good addition to the app:*

- A reset button for new rounds of game
- A counter for projectile (Shield x5) and poison defence (snooper x5),
Karama cards x4 (2 core game , 2 choam exp)




Kind regards

**Comment by MaxKolodziej** [comment]
@frike00 

I've added new version 1.3: https://drive.google.com/file/d/1PnHq8K7FFmi8nokBtfFxhtWIML6zWvOa/view?usp=sharing
Changes:
- New factions : Ecaz & Moritani & new cards
- Filters when adding cards
- Discard pile

(I don't see those icons you posted)

**Comment by frike00** [comment]
just posted then on drive

https://drive.google.com/drive/folders/1F17oSEii8gY5VnQ39WmY3hqj5cCJ05vP

pon, 11. pro 2023. 20:23 Maksymilian Kołodziej ***@***.***>
je napisao:

**Comment by frike00** [comment]
can you see the files?

kind regards

pon, 11. pro 2023. 20:48 Samir R ***@***.***> je napisao:

**Comment by MaxKolodziej** [comment]
@frike00 alright, I have access now :) I'll add those icons in around 2 weeks

**Comment by frike00** [comment]
Awesome, thank you so much!

sub, 16. pro 2023. 14:43 Maksymilian Kołodziej ***@***.***>
je napisao:

**Comment by frike00** [comment]
dont forget the reset option for setring up for new game session.

sub, 16. pro 2023. 22:02 Samir R ***@***.***> je napisao:

**Comment by frike00** [comment]
hi
long time no see.
have you been sucessful?

pet, 5. sij 2024. 13:07 Samir R ***@***.***> je napisao:

**Comment by mktiti** [comment]
Hey guys, sorry for being gone -- ha no time for personal projects.
Thanks so much for the new features and graphics!
I'll merge it, then will try to get some time to refactor the whole codebase a bit.

**Comment by MaxKolodziej** [comment]
@frike00  last update is on https://boardgamegeek.com/thread/3088374/updated-application-for-attreides-card-tracking
Unfortunately I don't have time to improve the app, for example with adding `reset` option. In case there will be additional cards or expansions I'll try to update it.

**Pull request merged**
